name: ItemCommandsPlus
main: com.github.amata1219.item.commands.plus.ItemCommandsPlus
version: 2.0.1
author: '@amata1219'
commands:
  ic+:
    description: It's main commands of this plugin.
    usage: /<command>
    permisson: item.commands.plus.icplus
    permissio-message: Yon don't have permission "<permission>"